name: tva
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python
  - numpy
  - opencv
  - matplotlib
  - ipykernel
  - faiss-cpu=1.8.0
  - tqdm
  - nbconvert
  - scipy
  - pytorch-cuda=11.8
  - torchmetrics
